import { defineConfig, devices } from "@playwright/test";

const PORT = 4322;
const CI = Boolean(process.env["CI"]);

/**
 * Runs against the built site (`dist/`) served by `astro preview`, so the
 * tests see exactly what GitHub Pages will serve. Build first: `npm test`
 * does both.
 */
export default defineConfig({
  testDir: "./tests/specs",
  outputDir: "./test-results",
  fullyParallel: true,
  forbidOnly: CI,
  retries: CI ? 1 : 0,
  reporter: [
    ["list"],
    ["html", { open: "never" }],
    // Read by scripts/ci-report.mjs to publish the run with the site.
    ["json", { outputFile: "reports/results.json" }],
  ],
  use: {
    baseURL: `http://127.0.0.1:${PORT}`,
    trace: "retain-on-failure",
  },
  expect: {
    toHaveScreenshot: { maxDiffPixelRatio: 0.01 },
  },
  // Baselines are per platform: Linux ones (used in CI) are generated by the
  // "Update visual baselines" workflow, never on a dev machine.
  snapshotPathTemplate:
    "tests/__screenshots__/{testFileName}/{arg}-{projectName}-{platform}{ext}",
  projects: [
    {
      name: "desktop",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 1440, height: 900 },
      },
    },
    {
      name: "mobile",
      use: { ...devices["Pixel 7"] },
    },
  ],
  webServer: {
    command: `npm run preview -- --port ${PORT} --host 127.0.0.1`,
    url: `http://127.0.0.1:${PORT}`,
    reuseExistingServer: !CI,
  },
});
